[tool.ruff]
line-length = 100
target-version = "py38"

select = [
  "F",   # pyflakes
  "E",   # pycodestyle
  "I",   # isort
  "W",
  "YTT", # flake8-2020
  "B",   # flake8-bugbear
  "Q",   # flake8-quotes
  "PLE", # pylint
  "PLW",
  "TID", # tidy imports
]

ignore = [
  "B019",
  # Within an except clause, raise exceptions with ...
  "B904",
  # Magic number
  "PLR2004",
]

[tool.ruff.isort]
known-third-party = ["wandb"]

[tool.ruff.per-file-ignores]
"examples/notebooks/*.py" = ["E402"]
